name: Nuget 'Krosoft.Extensions.Data' - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

resources:
  repositories:
    - repository: Krosoft.Extensions
      type: github
      name: krosoft-dev/Krosoft.Extensions
      endpoint: krosoft-dev

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src
      - Directory.Build.props

extends:
  template: tools/devops/templates/pipelines/nuget-template.yml@Krosoft.Extensions
  parameters:
    packages:
      - "Krosoft.Extensions.Data.Abstractions"
      - "Krosoft.Extensions.Data.EntityFramework"
      - "Krosoft.Extensions.Data.EntityFramework.InMemory"
      - "Krosoft.Extensions.Data.EntityFramework.PostgreSql"
      - "Krosoft.Extensions.Data.EntityFramework.SqlServer"
      - "Krosoft.Extensions.Data.EntityFramework.Sqlite"
      - "Krosoft.Extensions.Data.Json"
