// <auto-generated />
using System;
using Krosoft.Extensions.Samples.DotNet9.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Krosoft.Extensions.Samples.DotNet9.Api.Migrations
{
    [DbContext(typeof(SampleKrosoftContext))]
    [Migration("20251105203957_Groupe")]
    partial class Groupe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatutCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories", "Activite");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Libelle = "Catégorie 1",
                            StatutCode = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4560f48d-4d86-4b1e-8b22-51c1a9e3d6ca"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Libelle = "Catégorie 2",
                            StatutCode = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("789e4321-0987-4567-abcd-1234dcba5678"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Libelle = "Catégorie 3",
                            StatutCode = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("abcdef12-3456-7890-1234-567890abcdef"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Libelle = "Catégorie 4",
                            StatutCode = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Groupe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Groupes", "Activite");
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Langue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefaut")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Langues", "Systeme");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18d7ae90-4f13-4494-a120-19d3cf8c5821"),
                            Code = "fr",
                            IsActif = true,
                            IsDefaut = true,
                            Libelle = "fr"
                        },
                        new
                        {
                            Id = new Guid("18d7ae90-4f13-4494-a120-19d3cf8c5822"),
                            Code = "en",
                            IsActif = true,
                            IsDefaut = false,
                            Libelle = "Anglais"
                        });
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Logiciel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatutCode")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("GroupeId");

                    b.ToTable("Logiciels", "Activite");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Logiciel de lecture de fichiers PDF",
                            Nom = "Adobe Acrobat Reader",
                            StatutCode = 1,
                            TenantId = "Adobe",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("4560f48d-4d86-4b1e-8b22-51c1a9e3d6ca"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Logiciel de calcul de tableaux",
                            Nom = "Microsoft Excel",
                            StatutCode = 1,
                            TenantId = "Microsoft",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("1f39c60d-4f92-4f17-aa45-99e8f86a3b3a"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Premier logiciel",
                            Nom = "Logiciel1",
                            StatutCode = 1,
                            TenantId = "Fake_Tenant_Id",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("3e8f94fd-03ea-47b0-b8c5-20b14c361fce"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 2, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Deuxième logiciel",
                            Nom = "Logiciel2",
                            StatutCode = 2,
                            TenantId = "Fake_Tenant_Id",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("6c8a012b-cc8a-4da0-85a5-c9a87bb1a20a"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 3, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Troisième logiciel",
                            Nom = "Logiciel3",
                            StatutCode = 1,
                            TenantId = "Fake_Tenant_Id",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("9b5ccfd1-8c3e-4a0c-b4af-543a6f87042d"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Quatrième logiciel",
                            Nom = "Logiciel4",
                            StatutCode = 2,
                            TenantId = "Fake_Tenant_Id",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("c40e3ff1-4f3a-4a3a-8b0c-c52a45e6e7b6"),
                            CategorieId = new Guid("2a7c1a9d-6db3-4d1e-8d8b-9e8431d1b55c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            Description = "Cinquième logiciel",
                            Nom = "Logiciel5",
                            StatutCode = 1,
                            TenantId = "Fake_Tenant_Id",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        });
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Pays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pays", "Referentiel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aba289b9-bfd0-4ef5-a4b6-efc60812c001"),
                            Code = "fr",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("aba289b9-bfd0-4ef5-a4b6-efc60812c002"),
                            Code = "de",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("aba289b9-bfd0-4ef5-a4b6-efc60812c005"),
                            Code = "it",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("aba289b9-bfd0-4ef5-a4b6-efc60812c006"),
                            Code = "es",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        },
                        new
                        {
                            Id = new Guid("aba289b9-bfd0-4ef5-a4b6-efc60812c007"),
                            Code = "gb",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Systeme",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "Systeme"
                        });
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Statistique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasColumnType("text");

                    b.Property<int>("Nombre")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statistique");
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Logiciel", b =>
                {
                    b.HasOne("Krosoft.Extensions.Samples.Library.Models.Entities.Categorie", "Categorie")
                        .WithMany("Logiciels")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Krosoft.Extensions.Samples.Library.Models.Entities.Groupe", "Groupe")
                        .WithMany("Logiciels")
                        .HasForeignKey("GroupeId");

                    b.Navigation("Categorie");

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Categorie", b =>
                {
                    b.Navigation("Logiciels");
                });

            modelBuilder.Entity("Krosoft.Extensions.Samples.Library.Models.Entities.Groupe", b =>
                {
                    b.Navigation("Logiciels");
                });
#pragma warning restore 612, 618
        }
    }
}
